if (neatSrc) neatSrc.push({
    domainUrl: "https://grt.dozy.eu.org",
    backgrounds: [
        {from: "dev.png", name: "设备"},
        {from: "sky.png", name: "天空"},
        {from: "myth_lab.png", name: "圣所"},
        {from: "legend.png", name: "传奇"},
        {from: "sea_wave.png", name: "海浪"},
        {from: "white_mot.png", name: "白山"},
        {from: "aqua_mot.png", name: "青山"},
        {from: "purple_mot.png", name: "紫山"},
        {from: "wolf_mot.png", name: "狼山"},
        {from: "hask.png", name: "骇氩"},
        {from: "globe.png", name: "球体"},
        {from: "dusk.png", name: "黄昏"},
        {from: "brisand.png", name: "夜晚"},
        {from: "plants.png", name: "行星"},
        {from: "long.png", name: "长版"},
        {from: "flov.png", name: "支持"},
        {from: "oldbgp.svg", name: "旧版"}
    ],
    music: [
        {id: "Snow_Dayy", name: sc.sp, author: "The Tunnel"},
        {id: "China_X_Piano", name: sc.ep + "#China-X" + "(钢琴)".inc("w"), author: "徐梦圆".ank(sc.ra)},
        {id: "Enchanted_Forest", name: "Enchanted&nbsp".inc("y") + "Forest".inc("g") + "!!!".inc("a")},
        {id: "Bye_Bye_Lover", name: sc.lg},
        {id: "Invisible_Umbrella", name: sc.ep, author: "MoreanP".ank(sc.ra)},
{id: "Cyi4xia4si1xiang1", name: sc.sp + "#忆夏思乡", author: "MoreanP".ank(sc.ra)},
{id: "Escape_This_Moment", name: sc.ep, author: "LightScape"},
{id: "Hyperpop", name: sc.ra, author: "Glitchcore"},
{id: "Rokoy_City", name: sc.ep},
{id: "Autumn", name: sc.lg, author: "Kawaii".ank(sc.ra)},
{id: "Aftermath", name: sc.sp, author: "Adam Lambert"},
        {id: "Bgm_Sky_Block", name: sc.lg},
        {id: "Breezy_Street", name: sc.sp},
        {id: "Aqua_Start", name: sc.ra},
        {id: "Cloudy0a33", name: sc.ms},
        {id: "Space0a33", name: sc.ms},
        {id: "Storm0a33", name: sc.ms},
{id: "Infinity_Heaven", name: sc.ra, author: "HyuN"},
{id: "Je411v7pu", name: sc.sp},
{id: "Cwei4zhi1", name: sc.sp + "#未知"},
{id: "Bloody_A60", name: sc.ms, author: "praayy".ank(sc.ra)},
{id: "I_Love_You_3k_Times", name: sc.sp, author: "云上丝路"},
{id: "Pleasant_Advanture", name: sc.sp},
        {id: "Carrier32", name: sc.ot},
        {id: "Original_Soundtrack"},
        {id: "Background4"},
        {id: "Bgm_Sky_Wars", name: sc.ep},
        {id: "CharlieXCX", name: sc.lg, author: "cozin"},
        {id: "Em_Trap", name: sc.sp},
{id: "At_The_Edge", name: sc.ep, author: "空野リンジ&千坂"},
{id: "Come_Home", name: sc.lg, author: "DDRKirby(ISQ)".ank(sc.ra)},
{id: "Never_Forget_Me", name: sc.sp, author: "Senbeii"},
{id: "Funky_Stars", name: sc.ra, author: "Quazar"},
{id: "Carly_Paige", name: sc.lg, author: "3Lau Touch"},
{id: "Csheng4xia4de0sheng4xia4", name: sc.ep + "#剩下的盛夏", author: "TFBOYS"},
        {id: "Sad", name: sc.sp, author: "Егор Иксов"},
        {id: "Anan_Ryoko", name: sc.ms, author: "Refrain"},
        {id: "Pararrayos", name: sc.lg, author: "Valentin".ank(sc.ra)},
        {id: "Spark", name: sc.ra, author: "Ronald Jenkees".ank(sc.ms)},
        {id: "Cxing1cha2hui4", name: sc.ra + "#星茶会", author: "Kuroba"},
        {id: "Quiet3", name: sc.ot},
{id: "Cyue4", name: sc.ep + "#月", author: "郁可唯Yisa"},
{id: "Neon_Dreams", name: sc.ep, author: "Lofi"},
{id: "Heart_Beat", name: sc.sp, author: "Morrow"},
{id: "Decoy_World", author: "Intercom"},
{id: "Cgu1zhu2yi2meng4", name: sc.ep + "#孤竹遗梦", author: "徐梦圆".ank(sc.ra)},
{id: "Far_Away_Piano", name: sc.ep + "#Far Away" + "(钢琴)".inc("w"), author: "五月的钢琴声"},
        {id: "Brighter_Skies", name: sc.ep, author: "LightScape"},
        {id: "A_New_Start", name: sc.ep, author: "Rameses B"},
        {id: "Cjin3li3", name: sc.lg + "#锦鲤", author: "The Script"},
        {id: "Ya_Soshla_S_Uma", name: sc.sp, author: "T.A.T.u"}
    ]
});